<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <ProjectReference Include="..\Resenha.CrossCutting\Resenha.CrossCutting.csproj" />
    <ProjectReference Include="..\Resenha.Infrastructure\Resenha.Infrastructure.csproj" />
    <ProjectReference Include="..\Resenha.Modulo.Usuario.Application\Resenha.Modulo.Usuario.Application.csproj" />
    <ProjectReference Include="..\ResenhaWeb.Client\ResenhaWeb.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.0" />
  </ItemGroup>

</Project>
